import { ColumnVisibility, MedicalService } from "@/types/medical-service";

// export const medicalServices: MedicalService[] = [
//   {
//     hospital_name: "Bear River Valley Hospital",
//     address: "905 N 1000 W",
//     state: "UT",
//     code: "ICD-10-CM O80",
//     code_type: "Facility | Inpatient",
//     description: "Encounter for full-term uncomplicated delivery",
//     payer: "Medicare",
//     rate: 3000,
//     minimum: 2800,
//     maximum: 3200,
//     standard_charge_percentage: 0.8,
//     standard_charge_dollar: 2480,
//     list_price: 3123.0,
//     cash_rate: 2500,
//     additional_notes: "Standard delivery, no complications",
//     setting: "Inpatient",
//     relatedServices: [
//       {
//         code: "HCPCS 01967",
//         facilityType: "Facility | Inpatient & Outpatient",
//         description: "Neuraxl lbr anes vag dlvr",
//         price: 4011.0,
//       },
//       {
//         code: "HCPCS 59400",
//         facilityType: "Facility | Inpatient & Outpatient",
//         description: "Obstetrical care",
//         price: 1010.0,
//       },
//     ],
//   },
//   {
//     hospital_name: "Mckay-Dee Hospital",
//     address: "4401 Harrison Blvd",
//     state: "UT",
//     code: "ICD-10-CM O80",
//     code_type: "Facility | Inpatient",
//     description: "Encounter for full-term uncomplicated delivery",
//     payer: "Blue Cross",
//     rate: 3100,
//     minimum: 2900,
//     maximum: 3300,
//     list_price: 3245.0,
//     standard_charge_percentage: 0.8,
//     standard_charge_dollar: 2480,
//     cash_rate: 2600,
//     additional_notes: "Includes standard postpartum care",
//     setting: "Inpatient",
//     relatedServices: [
//       {
//         code: "HCPCS 59409",
//         facilityType: "Facility | Inpatient & Outpatient",
//         description: "Obstetrical care",
//         price: 602.1,
//       },
//       {
//         code: "HCPCS 59410",
//         facilityType: "Facility | Inpatient & Outpatient",
//         description: "Obstetrical care",
//         price: 300.2,
//       },
//     ],
//   },
//   {
//     hospital_name: "Test Hospital 1",
//     address: "123 Main St",
//     state: "NY",
//     standard_charge_percentage: 0.8,
//     standard_charge_dollar: 2480,
//     code: "ICD-10-CM O80",
//     code_type: "Facility | Inpatient",
//     description: "Test Description 1",
//     payer: "Test Payer 1",
//     rate: 2500,
//     minimum: 2300,
//     maximum: 2700,
//     list_price: 2600,
//     cash_rate: 2000,
//     additional_notes: "Test Notes 1",
//     setting: "Inpatient",
//     relatedServices: [],
//   },
//   {
//     hospital_name: "Test Hospital 1",
//     address: "123 Main St",
//     state: "NY",
//     code: "ICD-10-CM O80",
//     code_type: "Facility | Inpatient",
//     description: "Test Description 1",
//     payer: "Test Payer 1",
//     rate: 2500,
//     minimum: 2300,
//     maximum: 2700,
//     list_price: 2600,
//     cash_rate: 2000,
//     standard_charge_percentage: 0.8,
//     standard_charge_dollar: 2480,
//     additional_notes: "Test Notes 1",
//     setting: "Inpatient",
//     relatedServices: [],
//   },
//   {
//     hospital_name: "Test Hospital 1",
//     address: "123 Main St",
//     state: "NY",
//     code: "ICD-10-CM O80",
//     code_type: "Facility | Inpatient",
//     description: "Test Description 1",
//     payer: "Test Payer 1",
//     rate: 2500,
//     minimum: 2300,
//     maximum: 2700,
//     list_price: 2600,
//     standard_charge_percentage: 0.8,
//     standard_charge_dollar: 2480,
//     cash_rate: 2000,
//     additional_notes: "Test Notes 1",
//     setting: "Inpatient",
//     relatedServices: [],
//   },
//   {
//     hospital_name: "Test Hospital 1",
//     address: "123 Main St",
//     state: "NY",
//     code: "ICD-10-CM O80",
//     code_type: "Facility | Inpatient",
//     description: "Test Description 1",
//     payer: "Test Payer 1",
//     rate: 2500,
//     minimum: 2300,
//     maximum: 2700,
//     standard_charge_percentage: 0.8,
//     standard_charge_dollar: 2480,
//     list_price: 2600,
//     cash_rate: 2000,
//     additional_notes: "Test Notes 1",
//     setting: "Inpatient",
//     relatedServices: [],
//   },

//   {
//     hospital_name: "Test Hospital 2",
//     address: "456 Oak Ave",
//     state: "CA",
//     code: "ICD-10-CM O80",
//     code_type: "Facility | Outpatient",
//     description: "Test Description 2",
//     payer: "Test Payer 2",
//     rate: 3000,
//     minimum: 2800,
//     maximum: 3200,
//     list_price: 3100,
//     standard_charge_percentage: 0.8,
//     standard_charge_dollar: 2480,
//     cash_rate: 2500,
//     additional_notes: "Test Notes 2",
//     setting: "Outpatient",
//     relatedServices: [],
//   },
//   {
//     hospital_name: "Test Hospital 3",
//     address: "789 Pine Ln",
//     state: "TX",
//     code: "ICD-10-CM O80",
//     code_type: "Pro | Inpatient",
//     description: "Test Description 3",
//     payer: "Test Payer 3",
//     rate: 3500,
//     minimum: 3300,
//     maximum: 3700,
//     list_price: 3600,
//     standard_charge_percentage: 0.8,
//     standard_charge_dollar: 2480,
//     cash_rate: 3000,
//     additional_notes: "Test Notes 3",
//     setting: "Inpatient",
//     relatedServices: [],
//   },
// ];

export const defaultColumnVisibility: ColumnVisibility = {
  hospital_name: true,
  address: true,
  state: false,
  code: true,
  code_type: false,
  description: true,
  payer: false,
  rev_code: false,
  standard_charge_algorithm: false,
  estimated_amount: false,
  standard_charge_percentage: false,
  standard_charge_dollar: false,
  // rate: false,
  minimum: false,
  maximum: false,
  list_price: true,
  cash_rate: true,
  additional_notes: false,
  setting: false,
};
